final/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'asteroids' => 'asteroids#index'
  get 'data' => 'asteroids#retrieve'
  
  get 'favorites' => 'favorites#index'
  get '/favorites/:asteroid/destroy' => 'favorites#destroy', as: :remove_favorite
  get '/favorites/:asteroid' => 'favorites#add'
  
  get 'updateDB' => 'application#updateDB'

  root 'application#index'

end

final/app/models/asteroid.rb
class Asteroid < ApplicationRecord
    has_many :approaches
    has_and_belongs_to_many :users
    
    def next_earth_approach
        next_app = self.approaches.by_orbiting_body('Earth').next_approach[0]
        if next_app
            next_app["close_approach_date"]                    
        else
            'N/A'
        end
    end
    
    def next_earth_vel
        next_app = self.approaches.by_orbiting_body('Earth').next_approach[0]
        if next_app
            next_app["relative_velocity"].round(2)                 
        else
            'N/A'
        end
    end
    
    def format_to_NAPI 
        parsed = self.as_json
        parsed["estimated_diameter"] = {
            meters: {
                estimated_diameter_max: parsed["estimated_diameter_max"],
                estimated_diameter_min: parsed["estimated_diameter_min"]
            }
        }
        parsed["orbital_data"] = {
            orbit_id: parsed["orbit_id"],
            orbit_determination_date: parsed["orbit_determination_date"],
            orbit_uncertainty: parsed["orbit_uncertainty"],
            minimum_orbit_intersection: parsed["minimum_orbit_intersection"],
            jupiter_tisserand_invariant: parsed["jupiter_tisserand_invariant"],
            epoch_osculation: parsed["epoch_osculation"],
            eccentricity: parsed["eccentricity"],
            semi_major_axis: parsed["semi_major_axis"],
            inclination: parsed["inclination"],
            ascending_node_longitude: parsed["ascending_node_longitude"],
            orbital_period: parsed["orbital_period"],
            perihelion_distance: parsed["perihelion_distance"],
            perihelion_argument: parsed["perihelion_argument"],
            aphelion_distance: parsed["aphelion_distance"],
            perihelion_time: parsed["perihelion_time"],
            mean_anomaly: parsed["mean_anomaly"],
            mean_motion: parsed["mean_motion"],
            equinox: parsed["equinox"]
        }
        parsed
    end
    
    def self.search(search)
      if search
        where ['name LIKE ?', "%#{search}%"]
      else
        all
      end
    end
end

final/app/controllers/asteroids_controller.rb
class AsteroidsController < ApplicationController
    include SmartListing::Helper::ControllerExtensions
    helper SmartListing::Helper

  # GET /asteroids
  def index
    asteroids_scope = Asteroid.all
    if params[:filter]
        # search by name
        asteroids_scope = Asteroid.where("name LIKE ?", "%#{params[:filter]}%")
    end
    # use gon gem to pass variables to javascript
    gon.asteroids = '{}'
    gon.planets = '{}'

    # if user is not signed in, just display any 5 asteroids
    diag_ast = asteroids_scope.limit(5);

    if user_signed_in?
      diag_ast = current_user.asteroids
    end

    # reformat the data because our model is different from NASA's
    gon.asteroids = diag_ast.map { | x | x.format_to_NAPI }

    # get planet data
    # https://ssd.jpl.nasa.gov/txt/p_elem_t1.txt
    f = File.read("public/planets.json")
    gon.planets = JSON.parse(f)

    @asteroids = smart_listing_create(:asteroids, asteroids_scope, partial: "asteroids/table", default_sort: {is_potentially_hazardous_asteroid: "desc"})

  end

  def show
  end

  # GET /data.json
  def retrieve
    @asteroids = Asteroid.all
    respond_to do |format|
        format.json  { render :json => @asteroids }
    end
  end

end

final/app/views/asteroids/_table.html.erb
<%= smart_listing_controls_for(:asteroids) do %>
<div class="filter input-append">
    <%= text_field_tag :filter, '', class: "search", placeholder: "Search all NEOs", autocomplete: "off" %>
</div>
<% end%>
<% unless smart_listing.empty?%>
  

  
<table class="table">
  <thead>
    <tr>
      <th><%= smart_listing.sortable "Name", :name %></th>
      <th><%= smart_listing.sortable "NEO ID", :neo_reference_id %></th>
      <th><%= smart_listing.sortable "Potentially Hazardous?", :is_potentially_hazardous_asteroid %></th>
      <th><%= smart_listing.sortable "Estimated Diameter (m)", :estimated_diameter_min %></th>
      <th>Next Close Approach (CA) to Earth</th>
      <th>Relative Velocity at CA (km/s)</th>
    </tr>
  </thead>

  <tbody>
    <% smart_listing.collection.each do |asteroid| %>
        <tr class="asteroid" id=<%= 'asteroid-'+asteroid.id.to_s%>, role="button", data-toggle="collapse", data-parent="asteroid", class="expand-asteroid", href="#collapse<%= asteroid.id %>", aria-expanded="true" aria-controls="collapse<%= asteroid.id %>">
            <td><%= asteroid.name %></td>
            <td><%= asteroid.id %></td>
            <td><%= asteroid.is_potentially_hazardous_asteroid %></td>
            <td><%= asteroid.estimated_diameter_min.round(2) %> - <%= asteroid.estimated_diameter_max.round(2) %></td>
            <td><%= asteroid.next_earth_approach %></td>
            <td><%= asteroid.next_earth_vel %></td>
        </tr>
        <tr id='collapse<%= asteroid.id %>', class='collapse' aria-labelledby="collapse"<%= asteroid.id %>>
            <td class="collapse-cell" colspan="2"></td>
            <td class="collapse-cell">JPL web page:</td>
            <td class="collapse-cell"><%= link_to asteroid.nasa_jpl_url, asteroid.nasa_jpl_url %></td>
            <td class="collapse-cell"></td>
            <td class="collapse-cell"><%= link_to "Add to favorites", favorites_path + "/" + asteroid.id.to_s %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= smart_listing.paginate %>
<% else%>
    <p class="warning">No records!</p>
<% end%>

final/app/views/asteroids/_visualization.html.erb
<%= stylesheet_link_tag 'visualization' %>

<div id='viscontainer'></div>
  <%= javascript_include_tag 'visualization' %>
  

final/app/views/asteroids/index.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<%= render "visualization" %>


<%= smart_listing_render(:asteroids) %>


<br>

<p> CONTROLS: Hold left-click to rotate; Hold right-click to pan; Mouse wheel to zoom</p>

</div>

final/app/views/asteroids/index.js.erb
<%= smart_listing_update(:asteroids) %>