final/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'asteroids' => 'asteroids#index'
  get 'data' => 'asteroids#retrieve'
  
  get 'favorites' => 'favorites#index'
  get '/favorites/:asteroid/destroy' => 'favorites#destroy', as: :remove_favorite
  get '/favorites/:asteroid' => 'favorites#add'
  
  get 'updateDB' => 'application#updateDB'

  root 'application#index'

end

final/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  def check_user
    if !user_signed_in?
      redirect_to asteroids_path
    else
      @favorites = current_user.asteroids
    end
  end
  def index
    # show a list of user's saved asteroids
  end

  def show
  end
  def add
    ast = params[:asteroid]
    if current_user.asteroids.where("id = ?", ast.to_i).empty?
        current_user.asteroids << Asteroid.find(ast)
    end
    redirect_to favorites_path
  end
  def destroy
      current_user.asteroids.delete(Asteroid.find(params[:asteroid]))
      redirect_to favorites_path
  end

end

final/app/views/favorites/index.html.erb
<div class="container-fluid">
    <h1>Favorites</h1>
    <table class="table">
        <thead>
            <tr>
              <th>Name</th>
              <th>NEO ID</th>
              <th>Potentially Hazardous?</th>
              <th>Estimated Diameter (m)</th>
              <th>Next Close Approach (CA) to Earth</th>
              <th>Relative Velocity at CA (km/s)</th>
            </tr>
        </thead>
        <tbody>
        <% @favorites.each do |asteroid| %>
            <tr class="asteroid" id=<%= 'asteroid-'+asteroid.id.to_s%>, role="button", data-toggle="collapse", data-parent="asteroid", class="expand-asteroid", href="#collapse<%= asteroid.id %>", aria-expanded="true" aria-controls="collapse<%= asteroid.id %>">
                <td><%= asteroid.name %></td>
                <td><%= asteroid.id %></td>
                <td><%= asteroid.is_potentially_hazardous_asteroid %></td>
                <td><%= asteroid.estimated_diameter_min.round(2) %> - <%= asteroid.estimated_diameter_max.round(2) %></td>
                <td><%= next_app = asteroid.approaches.by_orbiting_body('Earth').next_approach[0]
                        if next_app
                            next_app["close_approach_date"]                    
                        else
                            'N/A'
                        end
                %></td>
                <td><%= next_app = asteroid.approaches.by_orbiting_body('Earth').next_approach[0]
                        if next_app
                            next_app["relative_velocity"].round(2)                 
                        else
                            'N/A'
                        end
                %></td>
            </tr>
            <tr id='collapse<%= asteroid.id %>', class='collapse' aria-labelledby="collapse"<%= asteroid.id %>>
                <td class="collapse-cell">JPL web page:</td>
                <td class="collapse-cell"><%= link_to asteroid.nasa_jpl_url, asteroid.nasa_jpl_url %></td>
                <td class="collapse-cell" colspan="3"></td>
                <td class="collapse-cell"><%= link_to "Remove from favorites", remove_favorite_path(asteroid.id.to_s) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
    
    
</div>