list/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :comments

  root 'application#index'
  get '/posts/sort/:type' => 'posts#sort'

end

list/app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true, length: { maximum: 140, message: "too long" }
    belongs_to :user
    belongs_to :post
end

list/app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    validates :category, presence: true
    belongs_to :user
    has_many :comments
    
    def self.search(search)
      if search
        where ['title LIKE ?', "%#{search}%"]
      else
        all
      end
    end
end

list/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  def index
    @title = 'Welcome!'
    puts '### GOT HERE'
    puts "### #{ @title }"
  end
  
  protected
  def configure_permitted_parameters
    added_attrs = [:name]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

list/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def check_user
    if current_user != @comment.user
      redirect_to comments_path
    end
  end

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    if user_signed_in?
      @comments = current_user.comments
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(comment_params[:post_id])
    @comment = current_user.comments.create!(comment_params)
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

list/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def check_user
    if current_user != @post.user
      redirect_to posts_path
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    if params[:search] && !params[:search].empty?
      @posts = Post.search(params[:search])
    else
      @posts = Post.all
    end
    if defined? @@sorter
      @posts = @posts.order(@@sorter[0] + (@@sorter[1]? '':' desc'))
    # @posts = Post.includes(:comments).order("comments.created_at desc")
    end
  end
  
  def sort
    ty = "#{params[:type]}"
    
    if defined? @@sorter
      if @@sorter[0] == ty
        @@sorter[1] = !@@sorter[1]
      else
        @@sorter = [ty, true]
      end
    else
      @@sorter = [ty, true]
    end
    redirect_to posts_path
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)
    #@post.user = current_user
    @post = current_user.posts.create!(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category)
    end
end

list/app/helpers/comments_helper.rb
module CommentsHelper
end

list/app/helpers/posts_helper.rb
module PostsHelper
end

list/app/views/application/index.html.erb
<div class="container-fluid">
    
    <image src="http://smithmeadows.com/wp-content/uploads/2012/04/P4250007.jpg" alt="posts" style="width:100%;">
    <div class="app-main well">
    <div class="container text-center"><%= link_to "See our posts", posts_path %></div>
    </div>
</div>

list/app/views/comments/_comment.html.erb
<div class="comment well" id=<%= 'comment-'+comment.id.to_s%>>
    
        <%= link_to 'Edit', edit_comment_path(comment) %> | <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <%= comment.created_at %> | 
        <strong><%= comment.user.name %>:</strong>
        <%= comment.content %>
        
    
</div>

list/app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <%= f.hidden_field :post_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

list/app/views/comments/edit.html.erb
<div class="container-fluid">
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>
</div>

list/app/views/comments/index.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<h1>Your Comments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Post</th>
      <th>Comment</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><strong><%= link_to comment.post.title, comment.post %></strong></td>
        <td><%= comment.content %></td>
        <td><%= comment.created_at %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

</div>

list/app/views/comments/new.html.erb
<div class="container-fluid">
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', @comment.post %>
</div>

list/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><%= link_to "WELCOME", root_path %></li>
        <li><%= link_to "POSTS", posts_path %></li>
        <li><%= link_to "NEW POST", new_post_path %></li>
        <% if user_signed_in?-%>
          <li><%= link_to "YOUR COMMENTS", comments_path %></li>
          <li><%= link_to "EDIT ACCOUNT", edit_user_registration_path %></li>
          <li><%= link_to "SIGN OUT", destroy_user_session_path, method: 'delete' %></li>
        <% else -%>
          <li><%= link_to "SIGN IN", new_user_session_path %></li>
          <li><%= link_to "REGISTER", new_user_registration_path %></li>
        <% end -%>
      </ul>
    </div>
  </nav>
<%= yield %>

</body>
</html>

list/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

list/app/views/posts/edit.html.erb
<div class="container-fluid">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

list/app/views/posts/index.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class='container-fluid well-lg'>
<%= form_tag posts_path, :method => 'get'  do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search"  %>
<% end %>
</div>
<table class="table">
  <thead>
    <tr>
      <th class="well">Sort:</th>
      <th><%= link_to 'Title', posts_path + '/sort/title' %></th>
      <th>Content</th>
      <th>User</th>
      <th><%= link_to 'Category', posts_path + '/sort/category' %></th>
      <th><%= link_to 'Date', posts_path + '/sort/created_at' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <div class="post" id=<%= 'post-'+post.id.to_s%>>
      <tr>
        <td></td>
        <td><%= link_to post.title, post %></td>
        <td><%= post.content.slice(0,100) %></td>
        <td><%= post.user.name %></td>
        <td><%= post.category %></td>
        <td><%= post.created_at %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </div>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn well center-block"><%= link_to 'New Post', new_post_path %></div>

</div>

list/app/views/posts/new.html.erb
<div class="container-fluid">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

list/app/views/posts/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1><%= @post.title %></h1>
  <div>
  <strong>Category:</strong>
  <%= @post.category %>
  </div>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to "Add Comment", new_comment_path(post_id: @post.id) %> |
  <%= link_to 'Back', posts_path %>
  
  <div class="well">
    <%= @post.content %>
  </div>
  

  

    <h4>Comments:</h4>
    <p>
    <%= render @post.comments %>
  </p>

</div>